x-common-env: &common-env
  SECRET: "esta_es_mi_compleja_clave_secreta"

services:

  api-gateway:
    build: ./api-gateway
    ports:
      - "9090:9090"
    environment:
      <<: *common-env
    depends_on:      
      - ms-usuario
      - ms-dueno
      - ms-mascota
      - ms-personal
      - ms-cita
      - ms-hospitalizacion
      - ms-resultados-examenes
      - ms-farmacia
      - ms-ventas
      - ms-pago
  ms-usuario:
    build: ./ms-usuario
    ports:
      - "8091:8091"
    environment:
      <<: *common-env

  ms-dueno:
    build: ./ms-dueno
    ports:
      - "8082:8082"
    environment:
      <<: *common-env

  ms-mascota:
    build: ./ms-mascota
    ports:
      - "8083:8083"
    environment:
      <<: *common-env

  ms-personal:
    build: ./ms-personal
    ports:
      - "8084:8084"
    environment:
      <<: *common-env

  ms-cita:
    build: ./ms-cita
    ports:
      - "8085:8085"
    environment:
      <<: *common-env
    
  ms-hospitalizacion:
    build: ./ms-hospitalizacion
    ports:
      - "8086:8086"
    environment:
      <<: *common-env

  ms-resultados-examenes:
    build: ./ms-resultados-examenes
    ports:
      - "8087:8087"
    environment:
      <<: *common-env

  ms-farmacia:
    build: ./ms-farmacia
    ports:
      - "8088:8088"
    environment:
      <<: *common-env

  ms-ventas:
    build: ./ms-ventas
    ports:
      - "8089:8089"
    environment:
      <<: *common-env

  ms-pago:
    build: ./ms-pago
    ports:
      - "8090:8090"
    environment:
      <<: *common-env