spring:
  application:
    name: ms-mascota
  datasource:
    url: jdbc:mysql://localhost:3306/vet_mascota_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: tu_contraseña
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083