spring.application.name=ms-pago
server.port=8090
 

spring.datasource.url=jdbc:mysql://localhost:3306/db_pago?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
 
# ─── JPA / Hibernate ──────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
 
# ─── Liquibase 
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog.sql
 
# ─── Feign Clients ────────────────────────────────────────────
api.venta.url=http://localhost:8089
api.dueno.url=http://localhost:8082
 
# ─── Swagger / OpenAPI ────────────────────────────────────────
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
