spring.application.name=api-gateway
server.port=8080

spring.cloud.gateway.routes[0].id=ms-usuario
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/usuario/**

spring.cloud.gateway.routes[1].id=ms-dueno
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/dueno/**

spring.cloud.gateway.routes[3].id=ms-mascota
spring.cloud.gateway.routes[3].uri=http://localhost:8083
spring.cloud.gateway.routes[3}.predicates[0]=Path=/api/v1/mascota/**

spring.cloud.gateway.routes[4].id=ms-personal
spring.cloud.gateway.routes[4].uri=http://localhost:8084
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/personal/**